[package]
name = "rad_message"
version = "0.1.0"
authors = ["nullptr"]
edition = "2018"

[dependencies]
chrono = "0"
lazy_static = "1"
nyx-space = "0"
ring = "0"
serde = { version = "1", features = ["derive"] }
